"""Ajout name

Revision ID: 413184630f8f
Revises: 
Create Date: 2024-02-23 02:13:23.483044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413184630f8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=70), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
